//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.BBFORMs = new HashSet<BBFORM>();
            this.BILLs = new HashSet<BILL>();
            this.CARTs = new HashSet<CART>();
            this.IMPORTs = new HashSet<IMPORT>();
            this.ORDER_BOOKS = new HashSet<ORDER_BOOKS>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string EMAILADDRESS { get; set; }
        public string USERPASS { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> ROLE { get; set; }
        public string IDCLASS { get; set; }
        public Nullable<decimal> TRIGIAGIOHANG { get; set; }
        public string ADDRESSS { get; set; }
        public string GENDER { get; set; }
        public string PHONENUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BBFORM> BBFORMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT> IMPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_BOOKS> ORDER_BOOKS { get; set; }
    }
}
