//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBFORM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BBFORM()
        {
            this.DETAIL_BBFORM = new HashSet<DETAIL_BBFORM>();
        }
    
        public int MAPHIEUMUON { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string MSSV { get; set; }
        public string TENKH { get; set; }
        public System.DateTime NGAYMUON { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_BBFORM> DETAIL_BBFORM { get; set; }
    }
}
