//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int MASACH { get; set; }
        public int MAKH { get; set; }
        public Nullable<int> SOLUONGHT { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual BOOK BOOK { get; set; }
    }
}
