//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int orderID { get; set; }
        public int bookID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual ORDER_BOOKS ORDER_BOOKS { get; set; }
    }
}
