//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATUS_ORDER()
        {
            this.ORDER_BOOKS = new HashSet<ORDER_BOOKS>();
        }
    
        public int statusId { get; set; }
        public string orderStatus { get; set; }
        public string COLOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_BOOKS> ORDER_BOOKS { get; set; }
    }
}
